name: Scrape F1 Articles

on:
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 3. Install Python dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Install Playwright system dependencies (CORRECTED)
      - name: Install Playwright system dependencies
        run: sudo python -m playwright install-deps # Use 'python -m' to ensure sudo can find it

      # 5. Install Playwright browsers
      - name: Install Playwright browsers
        run: playwright install

      # 6. Run scraper script
      - name: Run scraper script
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: python scraper.py

      # 7. Configure Git for commits
      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      # 8. Commit and push updated state file
      - name: Commit and Push updated URLs file
        run: |
          git add processed-urls.txt
          git diff --quiet --exit-code processed-urls.txt || git commit -m "Update processed URLs list"
          git push
